###
GET http://localhost:3200/api/grammages

###
GET http://localhost:3200/api/grammages?targetId=1

###
GET http://localhost:3200/api/grammages/1

###
POST http://localhost:3200/api/grammages
Content-Type: application/json

{
    "sample1" : 70,
    "sample2" : 70,
    "sample3" : 70,
    "sample4" : 70,
    "shiftId" : 1,
    "targetId": 1
}

###
PATCH http://localhost:3200/api/grammages/1
Content-Type: application/json

{
    "sample1" : 70,
    "sample2" : 70,
    "sample3" : 70,
    "sample4" : 70,
    "shiftId" : 1,
    "targetId": 2
}

###
DELETE http://localhost:3200/api/grammages/2