###
GET http://localhost:3200/api/groups

###
GET http://localhost:3200/api/groups?name=Group 1

###
GET http://localhost:3200/api/groups/1

###
POST http://localhost:3200/api/groups
Content-Type: application/json

{
    "name" : "Group 1"
}

###
PATCH http://localhost:3200/api/groups/1
Content-Type: application/json

{
    "name" : "Group 2"
}

###
DELETE http://localhost:3200/api/groups/2