###
GET http://localhost:3200/api/productions

###
GET http://localhost:3200/api/productions/1

###
POST http://localhost:3200/api/productions
Content-Type: application/json

{
    "mixResult" : 70,
    "additionBS" : 10,
    "grammage" : 70,
    "result" : 200,
    "waste" : 5,
    "groupId" : 1,
    "shiftId": 1,
    "targetId": 1
}

###
PATCH http://localhost:3200/api/productions/1
Content-Type: application/json

{
    "mixResult" : 70,
    "additionBS" : 10,
    "grammage" : 70,
    "result" : 300,
    "waste" : 3,
    "groupId" : 1,
    "shiftId": 1,
    "targetId": 1
}

###
DELETE http://localhost:3200/api/productions/2