###
GET http://localhost:3200/api/products

###
GET http://localhost:3200/api/products?name=Giv Biru

###
GET http://localhost:3200/api/products/1

###
POST http://localhost:3200/api/products
Content-Type: application/json

{
    "name" : "Giv Biru"
}

###
PATCH http://localhost:3200/api/products/1
Content-Type: application/json

{
    "name" : "Giv Ungu"
}

###
DELETE http://localhost:3200/api/products/2