###
GET http://localhost:3200/api/shifts

###
GET http://localhost:3200/api/shifts?startWorkingHourId=1&endWorkingHourId=3

###
GET http://localhost:3200/api/shifts/1

###
POST http://localhost:3200/api/shifts
Content-Type: application/json

{
    "startWorkingHourId": 1,
    "endWorkingHourId": 3,
    "name" : "Shift 1"
}

###
PATCH http://localhost:3200/api/shifts/1
Content-Type: application/json

{
    "startWorkingHourId": 4,
    "endWorkingHourId": 6,
    "name" : "Shift 15"
}

###
DELETE http://localhost:3200/api/shifts/2