###
GET http://localhost:3200/api/shifts

###
GET http://localhost:3200/api/shifts?time=72000000&name=Shift 15

###
GET http://localhost:3200/api/shifts/1

###
POST http://localhost:3200/api/shifts
Content-Type: application/json

{
    "time" :  72000000,
    "name" : "Shift 15"
}

###
PATCH http://localhost:3200/api/shifts/1
Content-Type: application/json

{
    "time" :  72000000,
    "name" : "Shift 15"
}

###
DELETE http://localhost:3200/api/shifts/2