###
GET http://localhost:3200/api/targets

###
GET http://localhost:3200/api/targets?mid=PO1234&date=2024-02-15T00:00:00.000Z&target=400

###
GET http://localhost:3200/api/targets/1

###
POST http://localhost:3200/api/targets
Content-Type: application/json

{
    "mid": "PO1234",
    "date": "2024-02-15",
    "target": 400,
    "productId": 1
}

###
PATCH http://localhost:3200/api/targets/1
Content-Type: application/json

{
    "mid": "PO1235",
    "date": "2024-02-16",
    "target": 500,
    "productId": 2
}

###
DELETE http://localhost:3200/api/targets/2