###
GET http://localhost:3200/api/users

###
GET http://localhost:3200/api/users?name=John Doe

###
GET http://localhost:3200/api/users/1

###
POST http://localhost:3200/api/users
Content-Type: application/json

{
    "name" : "John Doe",
    "email" : "john@gmail.com",
    "gender" : "Male"
}

###
PATCH http://localhost:3200/api/users/1
Content-Type: application/json

{
    "name" : "Dhea Fiky",
    "email" : "dhea@gmail.com",
    "gender" : "Female"
}

###
DELETE http://localhost:3200/api/users/2